version: 2

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    # Core linters
    - errcheck       # Check for unchecked errors
    - govet          # Reports suspicious constructs
    - ineffassign    # Detect ineffectual assignments
    - staticcheck    # Go static analysis
    - unused         # Check for unused code

    # Additional recommended linters
    - misspell       # Spelling mistakes
    - revive         # Fast, configurable linter
    - gosec          # Security problems
    - unconvert      # Remove unnecessary type conversions
    - gocyclo        # Cyclomatic complexity
    - gocognit       # Cognitive complexity
    - dupl           # Code cloning detection
    - goconst        # Repeated strings that could be constants
    - bodyclose      # Check HTTP response body is closed
    - nilerr         # Check for returning nil even if error is not nil
    - sqlclosecheck  # Check SQL rows/statements are closed
    - rowserrcheck   # Check for Rows.Err
    - wastedassign   # Find wasted assignment statements
    - whitespace     # Detect leading/trailing whitespace

linters-settings:
  gocyclo:
    min-complexity: 15

  gocognit:
    min-complexity: 20

  dupl:
    threshold: 100

  goconst:
    min-len: 3
    min-occurrences: 3

  misspell:
    locale: US

  revive:
    rules:
      - name: exported
        disabled: false
      - name: package-comments
        disabled: true  # Can be too strict for internal packages

  gosec:
    excludes:
      - G404  # Allow weak random number generator for non-crypto uses
    config:
      G101:
        pattern: "(?i)(password|secret|token|key|api_key)"
        ignore_entropy: false

issues:
  exclude-rules:
    # Exclude some linters from running on tests files
    - path: _test\.go
      linters:
        - gocyclo
        - dupl
        - gosec

    # Exclude generated code
    - path: db/db\.go
      linters:
        - unused
        - deadcode
    - path: db/models\.go
      linters:
        - unused
        - deadcode
    - path: db/query\.sql\.go
      linters:
        - unused
        - deadcode
        - goconst
        - gocyclo

    # Exclude templ generated files
    - path: _templ\.go
      linters:
        - unused
        - deadcode
        - goconst

  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true
